import Head from 'next/head'
import { useState, useEffect } from 'react'
import { search } from '@lyrasearch/lyra';
import { useMovieDB } from '../hooks/useMovie';

export default function Home() {

  const [input, setInput] = useState("");
  const [movies, setMovies] = useState({});
  const movieDB = useMovieDB();

  useEffect(() => {
    if (!movieDB) return;

    const searchResult = search(movieDB, {
      term: input,
      properties: '*',
    });
    setMovies(searchResult)

  }, [input, movieDB])

  const handleChange = (e) => {
    setInput(e.target.value)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Search:</h1>
        <input placeholder="Insert data" onChange={handleChange} value={input} />

        {
          movies?.hits?.map((movie, index) => {
            const { document: { title } } = movie;
            return (
              <li key={"movie-" + index}>{title}</li>
            )
          })
        }
      </div>
    </>
  )
}
